// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcxnoqcdhlgjufsaoqiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeG5vcWNkaGxnanVmc2FvcWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODU4NTUsImV4cCI6MjA2OTY2MTg1NX0.bDL5WfBgTW1zsDsVu58m2InrgZ61bV0ubLGmtW7C8zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});